### ISSUE TITLE
Add Algorithm in any preferred language

### ISSUE THREAD

**Issue by auralshin** [auralshin/competetive-code-hacktoberfest#24]
Add any algorithm in any language, add an languages folder if it's not already there.

You all can go ahead with your implementation most optimised code will be accepted. Keep referencing your PR here. Do star the repo for better reach

**Comment by anishjain94** [comment]
Added Binary Search Algos and Updated Folder Structure #28

**Comment by Hinal-Srivastava** [comment]
I'd like to add 2 in Python

**Comment by auralshin** [comment]
You all can go ahead with your implementation most optimised code will be accepted. Keep referencing your PR here. Do star the repo for better reach

**Comment by jayaganeshkumar** [comment]
Can I add the binary search algorithm here?
