### ISSUE TITLE
Sieve of Eratosthenes in C++

### ISSUE THREAD

**Issue by mauryahimanshu** [auralshin/competetive-code-hacktoberfest#35]
***Aim***: Implement Sieve of Eratosthenes in C++
-
Before submitting Pull Request:-
- [x] Check if the solution committed is giving the expected result

Good Luck.

**Comment by mauryahimanshu** [comment]
I would like to work on it.

**Comment by auralshin** [comment]
I'll check the PR and merge till then thanks for contributing

**Comment by mauryahimanshu** [comment]
I have submitted a pull request. Do check and merge.
