### ISSUE TITLE
Find Peak Element

### ISSUE THREAD

**Issue by busybee23** [auralshin/competetive-code-hacktoberfest#83]
****Very famous question in every tech round****

**Comment by busybee23** [comment]
@auralshin Please merge this soon, #84 is the solution already provided.

**Comment by priyak950** [comment]
In which language you required to get the solution?

**Comment by busybee23** [comment]
It's already provided in python.

**Comment by auralshin** [comment]
Finding peak element isn't a algorithm

**Comment by busybee23** [comment]
Sure I'll add them in python folder.
