### ISSUE TITLE
Add Linear/Binary Search in Java

### ISSUE THREAD

**Issue by Ashish7129** [auralshin/competetive-code-hacktoberfest#92]
Hi @auralshin,

Can I add a linear or binary search in java? or any other things you would like to add-in this

**Comment by auralshin** [comment]
if it's already there then try to improve the code or else please go forward @Ashish7129

**Comment by Ashish7129** [comment]
Hi @auralshin ,

I have added Linear search in Java Language, As Binary Search is already present.
